// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var ReasonReact = require("reason-react/src/legacy/ReasonReact.bs.js");
var App$ReasonTrial = require("./App.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReasonTrial.make([])), "root");

/*  Not a pure module */
